# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='age',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
