# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_auto_20170210_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
